import {
  mdiPlusNetworkOutline,
  mdiCheckBold,
  mdiTrashCanOutline,
  mdiHomeOutline,
  mdiSignPole,
  mdiLogout,
  mdiWeb,
  mdiWebOff,
  mdiChevronDown,
  mdiCloudRefreshOutline,
  mdiCloudUploadOutline,
  mdiCloudAlertOutline,
  mdiCloudSyncOutline,
  mdiCloudCheckOutline,
  mdiCellphone,
  mdiCheckAll,
  mdiClockOutline,
  mdiAlertOutline,
  mdiCloseThick,
  mdiCrosshairsGps,
  mdiCrosshairsQuestion,
} from '@mdi/js';

export default {
  mdiPlusNetworkOutline,
  mdiCheckBold,
  mdiTrashCanOutline,
  mdiHomeOutline,
  mdiSignPole,
  mdiLogout,
  mdiWeb,
  mdiWebOff,
  mdiChevronDown,
  mdiCloudRefreshOutline,
  mdiCloudUploadOutline,
  mdiCloudAlertOutline,
  mdiCloudSyncOutline,
  mdiCloudCheckOutline,
  mdiCellphone,
  mdiCheckAll,
  mdiClockOutline,
  mdiAlertOutline,
  mdiCloseThick,
  mdiCrosshairsGps,
  mdiCrosshairsQuestion,
};
